### ISSUE TITLE
boky/postfix:4.3.0-alpine (on Alpine host) no mechanism available - reopened

### ISSUE THREAD

**Issue by mauroreggio** [bokysan/docker-postfix#217] opened 2024-10-19 09:16 UTC
Hi bokysan and thanks for reply me.
Sorry because i not have the right skill for understand how create a container, so i not want bother you and waste your time.
I double check all and i not find config problem in my config.
Reading the tutorial you provide i can read something that tarickb write in the "debug session" of the project page:

> SASL Mechanisms
If Postfix complains about not finding a SASL mechanism (along the lines of warning: SASL authentication failure: No worthy mechs found), it's possible that either make install or the pre-built package put libsasl-xoauth2.so in the wrong directory.

This is exactly what happens to me.
I apreciate if anyone other that use this container with Microsoft 365, with OAUTH2, can say me that all works good, so i can concentrate me again in config problems.
I think that you do a great work with this project and if i can test OAUTH2 function and make it work, i think it become very important for permit send email with legacy application.

Thanks again.

_Originally posted by @mauroreggio in https://github.com/bokysan/docker-postfix/issues/215#issuecomment-2423710439_

**Comment by bokysan** [comment] 2024-10-19 19:12
This is a duplicate of #215, so I'm closing this ticket. Any further discussion should be made on that ticket.

**Closed by bokysan** 2024-10-19 19:12 UTC
