### ISSUE TITLE
Ingress support

### ISSUE THREAD

**Issue by mpetuska** [bokysan/docker-postfix#166] opened 2023-12-30 18:39 UTC
Hi, I'm trying to deploy this via helm and while everything does boot up fine inside the cluster, for whatever reason I cannot get my custom ingress with traefic controller to find an endpoint of the deployed service. It would be great if the chart itself would come with ingress configuration options or at least some sample setups how to properly achieve this. 

Here's my ingress definition in case you need it for debugging:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smtp
  namespace: smtp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - my.custom.domain
      secretName: smtp-tls
  rules:
    - host: my.custom.domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mail
                port:
                  name: smtp

```

With that traefic keeps complaining with these
```
level=error msg="Skipping service: no endpoints found" serviceName=mail providerName=kubernetes servicePort="&ServiceBackendPort{Name:smtp,Number:0,}" ingress=smtp namespace=smtp
```

**Comment by bokysan** [comment] 2023-12-30 20:34
I'm sorry. I'm not following what you're trying to achieve? Postfix does not offer HTTP/HTTPS interface, so there's nothing you can do with Ingress?

**Comment by mpetuska** [comment] 2023-12-30 21:01
I'm simply trying to expose postfix smtp port externally to be reachable from outside the cluster

**Comment by mpetuska** [comment] 2023-12-30 21:03
Although I see what you mean, my ingress is using http when it should just use raw tcp. I'll play around some more and report my findings. 

Regardless, it would still be nice to have built-in config options for exposing smtp port externally

**Comment by bokysan** [comment] 2023-12-30 21:32
I'm sorry, but what you're asking is our of scope and has nothing to do with this image. I'm closing the issue.


On what you're tying to achieve, I can only give you a word of advice, which is a completely kubernetes-related thing:

`Ingress`, by design was meant only for exposing HTTP traffic. You can't expose 'raw TCP', it simply does not work that way.

That being said, some Ingress controllers have specific extensions for exposing TCP and UDP ports. Check documentation of Traefik: https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/

**Closed** 2023-12-30 21:32 UTC

**Comment by mpetuska** [comment] 2023-12-31 01:28
Yeah, I've come to the same conclusion. Currently im trying to get a traefik IngressRouteTCP CRD working, but that would be way too opinionated to be included in this chart. However I still believe there's value in providing example configs for such CRDs under nginx and traefik controllers so others wouldn't have to waste as much time as I did (surely out-of-cluster access to smtp server is common enough usecase)

I'll share my final CRD config once I'm done testing in case you decide to include it in the README somewhere.
