### ISSUE TITLE
IPv6 name/address support: Address family not supported by protocol message in Logs since V4.0.1

### ISSUE THREAD

**Issue by frankhetterich** [bokysan/docker-postfix#153] opened 2023-11-01 13:39 UTC
Since Version 4.0.1 there is a Warning in the logs which i did not spot in older releases:

`warning: inet_protocols: disabling IPv6 name/address support: Address family not supported by protocol`

I think the Message is related to the fact that we have no IPv6 support in our K8s clusters. The message disappears when i set postfix.inet_protocols: to "ipv4" in the values.yaml

**Comment by bokysan** [comment] 2023-12-29 14:11
This is most likely related to switch from Alpine to Debian. Since you have no IPv6 support in your cluster, that warning seems on point.

Not quite sure what you expect me to do about it, though? :-|

**Comment by bokysan** [comment] 2024-01-07 09:51
Closing this as there's no reply and this is not a bug but intended functionality.

**Closed by bokysan** 2024-01-07 09:51 UTC

**Comment by frankhetterich** [comment] 2024-01-08 08:11
My Post was meant to be informative and i did not expect that you fix anything. But i thought that it could be that it´s an unwanted or unknown  behavior. 

So everything is also fine from my side
